# Change these first
owner: edwardcox # Your GitHub organization or username, where this repository lives
repo: scintera # The name of this repository
user-agent: edwardcox

sites:
  - name: scintera.com.au
    url: https://scintera.com.au
    icon: https://cdn.shopify.com/s/files/1/0541/0232/7477/files/Scinter-Logo-383x51_540x.jpg?v=1634195328
    expectedStatusCodes:
      - 200
      - 201
      - 404
    maxResponseTime: 5000
    assignees:
      - edwardcox
    ![Uptime](https://img.shields.io/endpoint?url=https://github.com/edwardcox/scintera/blob/master/api/scintera-com-au/uptime.json)
    
  - name: Shopify
    url: https://shopify.com
    icon: https://cdn.shopify.com/shopifycloud/brochure/assets/brand-assets/shopify-logo-primary-logo-456baa801ee66a0a435671082365958316831c9960c480451dd0330bcdae304f.svg
    expectedStatusCodes:
      - 200
      - 201
      - 404
    maxResponseTime: 5000
    
  - name: Shopify Accounts
    url: https://accounts.shopify.com
    icon: https://cdn.shopify.com/shopifycloud/brochure/assets/brand-assets/shopify-logo-monotone-black-6bded589fa6172f888c4b4f6ae1eca654e865dbb93271f7e2b94a563749aeb40.svg
    expectedStatusCodes:
      - 200
      - 201
      - 404
    maxResponseTime: 5000
    
  - name: Shopify Admin Area
    url: https://scintera-pty-ltd.myshopify.com/admin
    icon: https://cdn.shopify.com/shopifycloud/brochure/assets/brand-assets/shopify-logo-monotone-black-6bded589fa6172f888c4b4f6ae1eca654e865dbb93271f7e2b94a563749aeb40.svg
    expectedStatusCodes:
      - 200
      - 201
      - 404
    maxResponseTime: 5000
    
  - name: CloudFlare (DNS and CDN)
    url: https://cloudflare.com
    icon: https://download.logo.wine/logo/Cloudflare/Cloudflare-Logo.wine.png
    
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/800px-Google_%22G%22_Logo.svg.png
    
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/800px-Google_%22G%22_Logo.svg.png
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: scintera.siteauditpro.com.au
  # baseUrl: /your-repo-name
  logoUrl: https://i0.wp.com/siteauditpro.com.au/wp-content/uploads/2022/06/SAP-LOGO-189x60-px-1.png?w=189&ssl=1
  name: SiteAudit Pro Status Monitor
  introTitle: "scintera.com.au is being monitored by SiteAudit Pro."
  introMessage: 24x7 awareness and alerting enabled.
  navbar:
    - title: Status
      href: /
      
  footer: This page is powered by [Upptime](https://upptime.js.org)
   
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
